### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by YKDuan47** [TwoOnefour/max_book#1]
Traceback (most recent call last):
  File "get_doc.py", line 86, in <module>
    get_doc.run()
  File "get_doc.py", line 34, in run
    t = re.search(re.compile("(?:senddate:)(.*),"), str(soup.select("script")[5].next)).groups()[0].replace("'", "").strip(" ")
AttributeError: 'NoneType' object has no attribute 'groups'
运行 python.exe get_doc.py https://max.book118.com/html/2022/0221/8024036103004057.shtm报错如上，请问是怎么处理哇

**Comment by TwoOnefour** [comment]
我等下看看

**Comment by TwoOnefour** [comment]
似乎是url改了逻辑，我用示范url也有这个问题，如果你急着用的话可以看看别人的项目能不能用，我修改需要一定时间，抱歉

Anai ***@***.***> 於 2023年9月21日週四 上午9:20寫道：

**Comment by YKDuan47** [comment]
好的好的 感谢

**Comment by TwoOnefour** [comment]
> Author

已在最新commit修复此问题，如果不介意请尝试一下

**Comment by TwoOnefour** [comment]
![image](https://github.com/TwoOnefour/max_book/assets/77989499/a6af19bb-e456-4459-b553-06307565bd29)

**Comment by YKDuan47** [comment]
我这边也好了，感谢！

**Comment by TwoOnefour** [comment]
不客气
